# Generated by Django 5.0.9 on 2024-10-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_address_alter_order_city_and_more"),
        ("recipe", "0003_recipe_available_recipe_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemRec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemsrec",
                        to="orders.order",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items_rec",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
