# Generated by Django 5.1.1 on 2024-10-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_subscriptionplan_recipebook_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
